### PR TITLE
fix: `no-unused-vars` is unexpectly disabled in non-editor environment

### LINKED ISSUE #255: `no-unused-vars` is unexpectly disabled in non-editor environment
The issue was introduced in https://github.com/RightCapitalHQ/frontend-style-guide/issues/20, we are not intended to disable `no-unused-vars` or `@typescript-eslint/no-unused-vars` in non-editor environment.

### PR DESCRIPTION
**Pull request by PinkChampagne17**
Fixes #255

### CODE REVIEW

File: packages/eslint-config/src/config/javascript.ts [hunk 1]
```diff
@@ -28,7 +28,6 @@ const config: TSESLint.FlatConfig.ConfigArray = [
 if (!isInEditorEnv()) {
   config.push({
     rules: {
-      'no-unused-vars': 'off',
```
Comment (frantic1048) [inline packages/eslint-config/src/config/javascript.ts:31]: According to the usage of [eslint-plugin-unused-imports](https://github.com/sweepline/eslint-plugin-unused-imports#usage), may we disable `no-unused-vars`/`@typescript-eslint/no-unused-vars ` and use `unused-imports/no-unused-vars` instead?

**Review by frantic1048 — APPROVED** [review]
